### ISSUE TITLE
Update to Terraria server 1.4

### ISSUE THREAD

**Issue by frederiktoft** [FMMT666/Dockerraria#1]
Would be great if the image is updated to support the "Journey's End" update :) Have been using this docker image on my Synology NAS for quite a while, so would avoid to switch to something else since this has been working so great for me.

**Comment by FMMT666** [comment]
Updated to 1.4.0.2.
Ready to pull, deploy and begin the final journey.

**Comment by frederiktoft** [comment]
Thank you :)
