### ISSUE TITLE
Update to version 1.4.1.1

### ISSUE THREAD

**Issue by frederiktoft** [FMMT666/Dockerraria#3]
Hopefully the last request as Re-logic is promising this is the final update :p Can you please update the server version to the latest v.1.4.1.1?
Thanks a lot!

**Comment by FMMT666** [comment]
Finally-latest-last update to 1.4.1.1 ready for inspection.
Princess ready to move in ...

![grafik](https://user-images.githubusercontent.com/3057791/97251716-a7dcc300-1808-11eb-9ab8-297e0d9010c3.png)

**Comment by frederiktoft** [comment]
Thanks a lot :)
