### ISSUE TITLE
Cannot connect to server with my Android smartphone 

### ISSUE THREAD

**Issue by Joerchi** [FMMT666/Dockerraria#4]
Hi all!
I've just installed this Terraria Server inside Docker on my Synology NAS to give it a try. It runs on default port 7777 and port forwarding is configured on my DSL router to reach my NAS in LAN. However, with the latest Android Terraria APK, I am not able to find my local server :-(. I checked port forwarding again and LAN settings but cannot find any mistake. Can it be a version incompatibility or is it clearly a networking misconfiguration on my side?

Terraria server reports as v1.4.1.2, Android game displays 1.4.0.5.1 (Build 514).
Screenshots are attached. 

Thanks, take care and all the best!
Jörg 

![Synology Docker Server](https://user-images.githubusercontent.com/5272745/100005691-a7185c00-2dc9-11eb-9a4f-cfe44a747f8e.png)
![Android Screenshot](https://user-images.githubusercontent.com/5272745/100005706-ac75a680-2dc9-11eb-879d-9d90285282af.jpg)

**Comment by FMMT666** [comment]
Phew, I don't know.
Until now I thought that the mobile versions don't allow crossplaying with the PC ones.

Unfortunately, I don't have an Android device with Terraria, so I cannot check this easily.
Guess I have to ask $CHILD3 tomorrow =) 

Let's see ...

**Comment by FMMT666** [comment]
Oh wait - are you looking for version 1.4.0.5?
I just saw that I forgot to update the tag in Docker.
This here is indeed server version 1.4.1.2.

If you are sure that your phone version should work with that
old version, drop me a note and I can create an old one.

**Comment by FMMT666** [comment]
Ok, was interested in that too and wasn't aware that there is a solution.
I built in the Mobile variant.

Tested and working with iOS and an Android gaming device.

Please notice the changes and the new "STARTMODE" environment variable.
You'll need this to fire up the Mobile server.

Have fun.

---
Oh, one more thing, that's not in the doc now:
Don't use "Local Server".
Use "Online" and enter the (presumably local) IP address of your Synology box.
Port is also 7777.
